<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>true</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Fsmb.Api.Usmle.Client\Fsmb.Api.Usmle.Client.csproj" />
  </ItemGroup>   
</Project>